/**
 * @class CardList
 * @classdesc A List of Addresses, generated by {@link ListFactory}.
 * @license Apache-2.0
 * @copyright 2014 
 */

var ListFactory = require('./ListFactory.js'); 
var AddressList = (ListFactory(require('./Address.js'), 'address', 'addresses')).makeList();

module.exports = AddressList;
