/**
 * @class CardList
 * @classdesc A List of credit cards, generated by {@link ListFactory}.
 * @license Apache-2.0
 * @copyright 2014 
 */

var ListFactory = require('./ListFactory.js'); 
var CardList = (ListFactory(require('./Card.js'), 'card')).makeList();

module.exports = CardList;
